basePath: /v1
definitions:
  dto.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  dto.UserDto:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
    type: object
  dto.VerifyTokenRequest:
    properties:
      idToken:
        type: string
    required:
    - idToken
    type: object
  entity.Attraction:
    properties:
      _links:
        $ref: '#/definitions/entity.Links'
      classifications:
        items:
          $ref: '#/definitions/entity.Classification'
        type: array
      externalLinks:
        $ref: '#/definitions/entity.ExternalLinks'
      id:
        type: string
      images:
        items:
          $ref: '#/definitions/entity.Image'
        type: array
      test:
        type: boolean
      type:
        type: string
      upcomingEvents:
        $ref: '#/definitions/entity.UpcomingEvents'
      url:
        type: string
    type: object
  entity.City:
    properties:
      name:
        type: string
    type: object
  entity.Classification:
    properties:
      family:
        type: boolean
      genre:
        $ref: '#/definitions/entity.Genre'
      primary:
        type: boolean
      segment:
        $ref: '#/definitions/entity.Segment'
      subGenre:
        $ref: '#/definitions/entity.SubGenre'
      subType:
        $ref: '#/definitions/entity.SubType'
      type:
        $ref: '#/definitions/entity.Type'
    type: object
  entity.Country:
    properties:
      countryCode:
        type: string
      name:
        type: string
    type: object
  entity.Dates:
    properties:
      spanMultipleDays:
        type: boolean
      start:
        $ref: '#/definitions/entity.StartDate'
      status:
        $ref: '#/definitions/entity.Status'
      timezone:
        type: string
    type: object
  entity.Embedded:
    properties:
      attractions:
        items:
          $ref: '#/definitions/entity.Attraction'
        type: array
      venues:
        items:
          $ref: '#/definitions/entity.Venue'
        type: array
    type: object
  entity.Event:
    properties:
      _embedded:
        $ref: '#/definitions/entity.Embedded'
      dates:
        $ref: '#/definitions/entity.Dates'
      id:
        type: string
      locale:
        type: string
      name:
        type: string
      priceRanges:
        items:
          $ref: '#/definitions/entity.PriceRange'
        type: array
      sales:
        $ref: '#/definitions/entity.Sales'
      type:
        type: string
    type: object
  entity.EventDetail:
    properties:
      _embedded:
        $ref: '#/definitions/entity.Embedded'
      _links:
        $ref: '#/definitions/entity.Links'
      classifications:
        items:
          $ref: '#/definitions/entity.Classification'
        type: array
      dates:
        $ref: '#/definitions/entity.Dates'
      id:
        type: string
      images:
        items:
          $ref: '#/definitions/entity.Image'
        type: array
      locale:
        type: string
      name:
        type: string
      sales:
        $ref: '#/definitions/entity.Sales'
      test:
        type: boolean
      type:
        type: string
      url:
        type: string
    type: object
  entity.ExternalLinks:
    properties:
      facebook:
        items:
          $ref: '#/definitions/entity.Link'
        type: array
      homepage:
        items:
          $ref: '#/definitions/entity.Link'
        type: array
      musicbrainz:
        items:
          $ref: '#/definitions/entity.Link'
        type: array
      wiki:
        items:
          $ref: '#/definitions/entity.Link'
        type: array
    type: object
  entity.Genre:
    properties:
      id:
        type: string
    type: object
  entity.Image:
    properties:
      fallback:
        type: boolean
      height:
        type: integer
      ratio:
        type: string
      url:
        type: string
      width:
        type: integer
    type: object
  entity.Link:
    properties:
      href:
        type: string
    type: object
  entity.Links:
    properties:
      attractions:
        items:
          $ref: '#/definitions/entity.Link'
        type: array
      self:
        $ref: '#/definitions/entity.Link'
      venues:
        items:
          $ref: '#/definitions/entity.Link'
        type: array
    type: object
  entity.PriceRange:
    properties:
      currency:
        type: string
      max:
        type: number
      min:
        type: number
    type: object
  entity.PublicSale:
    properties:
      endDateTime:
        type: string
      startDateTime:
        type: string
      startTBA:
        type: boolean
      startTBD:
        type: boolean
    type: object
  entity.Sales:
    properties:
      public:
        $ref: '#/definitions/entity.PublicSale'
    type: object
  entity.Segment:
    properties:
      id:
        type: string
    type: object
  entity.StartDate:
    properties:
      dateTBA:
        type: boolean
      dateTBD:
        type: boolean
      dateTime:
        type: string
      localDate:
        type: string
      localTime:
        type: string
      noSpecificTime:
        type: boolean
      timeTBA:
        type: boolean
    type: object
  entity.Status:
    properties:
      code:
        type: string
    type: object
  entity.SubGenre:
    properties:
      id:
        type: string
    type: object
  entity.SubType:
    properties:
      id:
        type: string
    type: object
  entity.Type:
    properties:
      id:
        type: string
    type: object
  entity.UpcomingEvents:
    properties:
      wts-tr:
        type: integer
    type: object
  entity.Venue:
    properties:
      city:
        $ref: '#/definitions/entity.City'
      country:
        $ref: '#/definitions/entity.Country'
      locale:
        type: string
      name:
        type: string
      postalCode:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: GigBuddy API Documentation
  title: GigBuddy API
  version: 1.0.0
paths:
  /events:
    get:
      description: Get event by keyword
      operationId: get-event-by-keyword
      parameters:
      - description: Keyword
        in: query
        name: keyword
        type: string
      - description: Location
        in: query
        name: location
        type: string
      - description: Page
        in: query
        name: page
        type: integer
      - description: Size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Return event successfully
          schema:
            $ref: '#/definitions/entity.Event'
      security:
      - AccessToken:
        - admin
        - user
      summary: Get event by keyword
      tags:
      - ticketmaster-event
  /events/{eventId}/join:
    post:
      description: Join event
      operationId: join-event
      parameters:
      - description: Event ID
        in: path
        name: eventId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Return event detail successfully
          schema:
            $ref: '#/definitions/entity.EventDetail'
      security:
      - AccessToken:
        - admin
        - user
      summary: Join event
      tags:
      - events
  /events/{eventId}/leave:
    post:
      description: Leave event
      operationId: leave-event
      parameters:
      - description: Event ID
        in: path
        name: eventId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Return event detail successfully
          schema:
            $ref: '#/definitions/entity.EventDetail'
      security:
      - AccessToken:
        - admin
        - user
      summary: Leave event
      tags:
      - events
  /events/{id}:
    get:
      description: Get event by id
      operationId: get-event-by-id
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Return event detail successfully
          schema:
            $ref: '#/definitions/entity.EventDetail'
      security:
      - AccessToken:
        - admin
        - user
      summary: Get event by id
      tags:
      - ticketmaster-event
  /events/user:
    get:
      description: Get event by user
      operationId: get-event-by-user
      produces:
      - application/json
      responses:
        "200":
          description: Return event detail successfully
          schema:
            $ref: '#/definitions/entity.EventDetail'
      security:
      - AccessToken:
        - admin
        - user
      summary: Get event by user
      tags:
      - events
  /identity/create:
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: CreateUserRequest
        in: body
        name: createUserRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses: {}
      summary: Create user
      tags:
      - identity
  /identity/userinfo:
    get:
      consumes:
      - application/json
      description: Get user info
      produces:
      - application/json
      responses:
        "200":
          description: Return user dto successfully
          schema:
            $ref: '#/definitions/dto.UserDto'
      security:
      - AccessToken:
        - admin
        - user
      summary: Get user info
      tags:
      - identity
  /identity/verify:
    post:
      consumes:
      - application/json
      description: Verify token
      parameters:
      - description: VerifyTokenRequest
        in: body
        name: verifyTokenRequest
        required: true
        schema:
          $ref: '#/definitions/dto.VerifyTokenRequest'
      produces:
      - application/json
      responses: {}
      summary: Verify token
      tags:
      - identity
securityDefinitions:
  AccessToken:
    in: header
    name: Authorization
    scopes:
      admin: Grants read and write access to administrative information
      user: Grants write access
    type: apiKey
swagger: "2.0"
